---
- name: copy reaml to job to host
  template:
    src: initial-realm.json.j2
    dest: /mnt/data_storage/keycloak/initial-realm.json
    mode: "0644"

- name: copy keycloak spec job to host
  template:
    src: keycloak.nomad.hcl
    dest: /tmp/keycloak.nomad
    mode: "0644"

- name: deploy keycloak in nomad
  shell: |
    nomad run /tmp/keycloak.nomad
  register: nomad_run_output
  changed_when: "'evaluation triggered' in nomad_run_output.stdout"

- name: output deploy after run
  debug:
    var: nomad_run_output.stdout
