---
- name: Install dnsmasq (RHEL/CentOS)
  yum:
    name: dnsmasq
    state: present
  when: ansible_os_family == "RedHat"

- name: Disable NetworkManager DNS management (CentOS/RHEL)
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^dns='
    line: 'dns=none'
    create: yes
  when: ansible_os_family == "RedHat"

- name: Restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Remove existing /etc/resolv.conf if present
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create new /etc/resolv.conf with dnsmasq as resolver
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 127.0.0.1
      nameserver 8.8.8.8
      nameserver 1.1.1.1
    owner: root
    group: root
    mode: '0644'

- name: Configure dnsmasq for Consul DNS forwarding
  copy:
    dest: /etc/dnsmasq.d/consul.conf
    content: |
      server=/consul/127.0.0.1#8600
      server=8.8.8.8
    owner: root
    group: root
    mode: '0644'

- name: Configure dnsmasq to listen on host IP as well as loopback
  copy:
    dest: /etc/dnsmasq.d/host.conf
    content: |
      listen-address=127.0.0.1,{{ ansible_default_ipv4.address }}
    owner: root
    group: root
    mode: '0644'

- name: Create custom resolv.conf file for docker containers (optional backup)
  copy:
    dest: /etc/custom_resolv.conf
    content: |
      nameserver {{ ansible_default_ipv4.address }}
      search service.consul
    owner: root
    group: root
    mode: '0644'

- name: Configure docker daemon with custom DNS settings
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "dns": ["{{ ansible_default_ipv4.address }}", "8.8.8.8"],
        "dns-search": ["service.consul"]
      }
    owner: root
    group: root
    mode: '0644'

- name: Restart docker
  systemd:
    name: docker
    state: restarted

- name: Restart dnsmasq service to apply changes
  systemd:
    name: dnsmasq
    state: restarted
    enabled: true
