---
- name: copy storage_api spec job to host
  template:
    src: storage_api.nomad.j2
    dest: /tmp/storage_api.nomad
    mode: "0644"

- name: deploy storage_api in nomad
  shell: |
    nomad run /tmp/storage_api.nomad
  register: nomad_run_output
  changed_when: "'evaluation triggered' in nomad_run_output.stdout"

- name: output deploy after run
  debug:
    var: nomad_run_output.stdout
