---
- hosts: apps
  become: yes
  roles:
    - role: nomad_jobs_open_policy
      constraint: "app1"

    - role: nomad_jobs_postgres
      constraint: "app2"
      postgres_user: "postgres"
      postgres_password: "S3gur0!"
      postgres_database: "postgres"

    - role: nomad_jobs_mongo
      constraint: "app2"
      mongo_user: "mongodb"
      mongo_password: "Cwiz$61P1z3@"

    - role: nomad_jobs_minio
      constraint: "app1"
      minio_user: "minio"
      minio_password: "BwiY|61P1z3("

    - role: nomad_jobs_camunda7
      constraint: "app1"

    - role: nomad_jobs_keycloak
      constraint: "app1"
      keycloak_user: "admin"
      keycloak_password: "admin"
      tls_cert_dir: "/mnt/data_storage"

    - role: nomad_jobs_traefik      