---
- name: copy postgres spec job to host
  template:
    src: postgres.nomad.hcl
    dest: /tmp/postgres.nomad
    mode: "0644"

- name: deploy postgres in nomad
  shell: |
    nomad run /tmp/postgres.nomad
  register: nomad_run_output
  changed_when: "'evaluation triggered' in nomad_run_output.stdout"

- name: output deploy after run
  debug:
    var: nomad_run_output.stdout
