---
- name: update apt cache
  apt:
    update_cache: yes

- name: install nginx on systems
  apt:
    name: nginx
    state: present

- name: create directory for tls certificates
  file:
    path: "{{ tls_cert_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: configure main nginx configuration file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: configure app with tls support
  template:
    src: templates/app.conf.j2
    dest: /etc/nginx/sites-available/app.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: enable production app
  file:
    src: /etc/nginx/sites-available/app.conf
    dest: /etc/nginx/sites-enabled/app.conf
    state: link
  notify: restart nginx    

- name: configure keycloak with tls support
  template:
    src: templates/kc.conf.j2
    dest: /etc/nginx/sites-available/kc.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: enable production keycloak
  file:
    src: /etc/nginx/sites-available/kc.conf
    dest: /etc/nginx/sites-enabled/kc.conf
    state: link
  notify: restart nginx    

- name: configure api with tls support
  template:
    src: templates/api.conf.j2
    dest: /etc/nginx/sites-available/api.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: enable production api
  file:
    src: /etc/nginx/sites-available/api.conf
    dest: /etc/nginx/sites-enabled/api.conf
    state: link
  notify: restart nginx    

- name: configure stg with tls support
  template:
    src: templates/stg.conf.j2
    dest: /etc/nginx/sites-available/stg.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: enable production stg
  file:
    src: /etc/nginx/sites-available/stg.conf
    dest: /etc/nginx/sites-enabled/stg.conf
    state: link
  notify: restart nginx        

- name: remove default site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx