---
- name: update apt cache
  apt:
    update_cache: yes

- name: install nginx on systems
  apt:
    name: nginx
    state: present

- name: create directory for tls certificates
  file:
    path: "{{ tls_cert_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: configure main nginx configuration file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: configure site with tls support
  template:
    src: templates/{{ item }}.conf.j2
    dest: /etc/nginx/sites-available/{{ item }}.conf
    owner: root
    group: root
    mode: '0644'
  loop:
    - api
    - app
    - camunda
    - kc
    - stg
  notify: restart nginx

- name: enable site
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  loop:
    - api
    - app
    - camunda
    - kc
    - stg
  notify: restart nginx

- name: remove default site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx