# general nginx configuration
nginx_worker_processes: auto
nginx_worker_connections: 1024

# directory for TLS certificates
tls_cert_dir: "/etc/nginx/ssl"
tls_crt_dest: "{{ tls_cert_dir }}/server.crt"
tls_key_dest: "{{ tls_cert_dir }}/server.key"