cni_plugins_version: "v1.3.0"
cni_plugins_arch: "amd64"
cni_plugins_os: "linux"
cni_plugins_filename: "cni-plugins-{{ cni_plugins_os }}-{{ cni_plugins_arch }}-{{ cni_plugins_version }}.tgz"
cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/{{ cni_plugins_filename }}"
cni_plugins_download_path: "/tmp/{{ cni_plugins_filename }}"
cni_plugins_extracted_path: "/tmp"
cni_plugins_install_dir: "/opt/cni/bin"