- name: copy the docker image file to the remote host
  ansible.builtin.copy:
    src: "/tmp/{{ image }}_{{ tag }}"
    dest: "/tmp/{{ image }}_{{ tag }}"
    mode: '0644'

- name: load the docker image on the remote host
  ansible.builtin.command:
    cmd: docker load -i /tmp/{{ image }}_{{ tag }}
  changed_when: true

- name: remove the temporary image file after loading
  ansible.builtin.file:
    path: "/tmp/{{ image }}_{{ tag }}"
    state: absent
