---
- name: Remove old Docker packages (Debian/Ubuntu)
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker.io
    - docker-engine
  when: ansible_os_family == "Debian"

- name: Remove old Docker packages (RHEL/CentOS)
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker.io
    - docker-engine
  when: ansible_os_family == "RedHat"

- name: Install dependencies (Debian/Ubuntu)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add Docker GPG key (Debian/Ubuntu)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  when: ansible_os_family == "Debian"

- name: Install dependencies (RHEL/CentOS)
  yum:
    name:
      - yum-utils
      - ca-certificates
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Docker repo (RHEL/CentOS)
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $releasever
    baseurl: >-
      https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install Docker (Debian/Ubuntu)
  apt:
    name: docker-ce
    state: present
  when: ansible_os_family == "Debian"

- name: Install Docker (RHEL/CentOS)
  yum:
    name: docker-ce
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user {{ ansible_user }} to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Ensure that the docker config directory is assigned to root
  file:
    path: /root/.docker
    state: directory
    mode: '0700'

- name: Configure docker to auth in the GCR
  template:
    src: docker_config.json
    dest: /root/.docker/config.json
    mode: '0600'

- name: Restart docker service to apply changes
  systemd:
    name: docker
    state: restarted
    enabled: true
