
---
- hosts: apps
  become: yes
  roles:
    - role: nomad_jobs_postgres
      constraint: "app2"
      postgres_user: "postgres"
      postgres_password: "S3gur0!"
      postgres_database: "postgres"
