
---
- hosts: apps
  become: yes
  roles:
    - role: nomad_jobs_keycloak
      constraint: "app1"
      keycloak_user: "admin"
      keycloak_password: "admin"
      tls_cert_dir: "/mnt/data_storage"
