---
- name: copy case_engine_api spec job to host
  template:
    src: case_engine_api.nomad.j2
    dest: /tmp/case_engine_api.nomad
    mode: "0644"

- name: deploy case_engine_api in nomad
  shell: |
    nomad run /tmp/case_engine_api.nomad
  register: nomad_run_output
  changed_when: "'evaluation triggered' in nomad_run_output.stdout"

- name: output deploy after run
  debug:
    var: nomad_run_output.stdout
